# Generated by Django 3.2.9 on 2021-11-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('punto', 'Punto'), ('enemy', 'Enemy'), ('wall', 'Wall'), ('ladder', 'Ladder')], max_length=255)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('born_date', models.DateTimeField(blank=True, null=True)),
                ('death_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.entity')),
            ],
            options={
                'verbose_name_plural': 'Enemies',
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.entity')),
                ('brain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.brain')),
            ],
            options={
                'verbose_name_plural': 'Punti',
            },
            bases=('entities.entity',),
        ),
    ]
